In [1]:
import matplotlib.pyplot as plt
import numpy as np
import discopy.util as util
import discopy.plot as plot
import discopy.geom as geom
from pathlib import Path
plt.style.use('ggplot')
import pandas as pd

In [29]:
def find_bad_segments(t):
    print("start")
    dt = t[1:] - t[:-1]
    restart_index = np.where(dt < 0)[0] + 1
    print(restart_index)
    bad_b = restart_index + 1
    bad_a = []
    good_a = 0
    for b in bad_b:
        result = np.searchsorted(t[good_a:b-1], t[b]) + good_a
        bad_a.append(result)
        good_a = b
    segs = list(zip(bad_a, bad_b))
    print(segs)
    return segs

def clean_bad_segments(bad_segs, data):
    mask = np.empty((data.shape[0]), dtype=bool)
    mask[:] = True
    for seg in bad_segs:
        mask[seg[0]:seg[1]] = False
    return data[mask]

    


In [30]:
t1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
t2 = np.array([0, 1, 2, 3, 4, 5, 4, 5, 6, 7, 8])
t3 = np.array([0, 0.1, 0.2, 0.3, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.4, 0.5, 0.6, 0.7, 0.8])
segs_1 = find_bad_segments(t1)
segs_2 = find_bad_segments(t2)
segs_3 = find_bad_segments(t3)

t1, clean_bad_segments(segs_1, t1), t2, clean_bad_segments(segs_2, t2), t3, clean_bad_segments(segs_3, t3)

start
[]
[]
start
[6]
[(5, 7)]
start
[ 4 10]
[(3, 5), (7, 11)]


(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0, 1, 2, 3, 4, 5, 4, 5, 6, 7, 8]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0. , 0.1, 0.2, 0.3, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.4, 0.5, 0.6,
        0.7, 0.8]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]))